CREATE TABLE items(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  brand TEXT,
  price DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
